# -*- coding: utf-8 -*-
"""projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zO-RFYC9n9e9EDjQSZ4wZaw2d3eI36CV
"""

Para a analise de dados, foi utilizado uma API da google om transações de cartão de crédito com fraudes dentro dela. Inicialmente, começamos importante os dados e então tendo uma visualização superficial dos dados.

import pandas as pd

url = "https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"

df = pd.read_csv(url)

df.head()

"""Com essa visualização, não é possível notar a olho nu possíveis fraudes. Então podemos ver uma proporção utilizando as classes. O modelo diz que a classe 0 não tem fraude enquanto a 1 tem. Porém, isso ainda não é o suficiente para confirmar o que é frause."""

df["Class"].value_counts(normalize=True)

"""Para isso, um modelo utilizado foi o da biblioteca sklearn junto com o numpy. Dessa forma, podemos verificar se transações são fraudes ou não com base no treinamento utilizando regressão logistica."""

import numpy as np

df["Amount_log"] = np.log1p(df["Amount"])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])

from sklearn.model_selection import train_test_split

X = df.drop("Class", axis=1)
y = df["Class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""É possível analiar que a precisão de acertos foi de 84% do modelo com treinamento para encontrar fraudes. Esse resultado pode ser utilizado para situções reais em analise de dados para detecção de fraudes ou até mesmo segurança."""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

y_probs = model.predict_proba(X_test)[:,1]

fpr, tpr, _ = roc_curve(y_test, y_probs)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

print("AUC", roc_auc_score(y_test, y_probs))

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_test, y_probs)

plt.plot(recall, precision)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

# Undersampling

fraudes = df[df["Class"] == 1]
normais = df[df["Class"] == 0].sample(len(fraudes), random_state=42)

df_under = pd.concat([fraudes, normais])

# Oversampling

from imblearn.over_sampling import SMOTE

smote = SMOTE()

X_res, y_res = smote.fit_resample(X, y)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
  n_estimators=50,
  max_depth=10,
  class_weight="balanced",
  n_jobs=-1,
  random_state=42
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print(classification_report(y_test, y_pred_rf))

from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

threshold = 0.3

y_pred_custom = (y_probs > threshold).astype(int)

print(classification_report(y_test, y_pred_custom))

Existe outro método de classificação que mais preciso e mais profissional, que é da biblioteca xgboost.

from xgboost import XGBClassifier

xgb = XGBClassifier(
    scale_pos_weight=10, # ajuda com desbalanceamento
    use_label_encoder=False,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print(classification_report(y_test, y_pred_xgb))

"""Analisando, podemos ver que ela conseguiu detectar 94% de fraudes em cartões de crédito. Esse então seria o modelo mais ideal para detecões de fraude ou segurança.

O importante sobre os modelos não são apenas os dados sendo extraidos, mas como utiliza-los para extrair esses dados de maneira correta, direta e com maior qualidade e desempenho possível.
"""

import matplotlib.pyplot as plt

importancias = xgb.feature_importances_

plt.bar(range(len(importancias)), importancias)
plt.title("Importância das variáveis")
plt.show()

from sklearn.model_selection import GridSearchCV

param_grid = {
    "max_depth": [3,5],
    "n_estimators":[50, 100]
}

grid = GridSearchCV(
    XGBClassifier(eval_metric="logloss"),
    param_grid,
    scoring="recall",
    cv=3
)

grid.fit(X_train, y_train)

print("Melhor modelo:", grid.best_params_)

import shap

explainer = shap.Explainer(xgb)
shap_values = explainer(X_test[:100])

shap.plots.bar(shap_values)